### ISSUE TITLE
A zero coefficient in H.txt or O.txt can lead to segmentation fault

### ISSUE THREAD

**Issue by naezzell** [LevBarash/PMRQMC#1]
## Minimal description of bug
A `0` coefficient in `H.txt` or `O.txt` can lead to a segmentation fault. 

## Minimal example where segmentation fault occurs
Define `H.txt` as
```
0.0 1 X
```
and then executing `./prepare.bin H.txt` leads to `[1]    20722 segmentation fault  ./prepare.bin H.txt`

## Minimal example where segmentation fault does not occur
On the other hand, defining `H.txt` as
```
1.0 1 X
1.0 1 Z
0.0 1 Y
```
allows one to execute `./prepare.bin H.txt` without any hangups. 

## Comment on H.txt or O.txt
The same set of failures/success seems to plague `H.txt` and `O.txt`. Though, in rare cases which I cannot reliably reproduce presently, I have also gotten a failure output
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Preparing PMR for the observables and their representation via the permutation operators of the Hamiltonian..../job_file.sh: line 3: 33701 Aborted                 ./prepare.bin H.txt $(ls O.txt O.txt O.txt O.txt O.txt O.txt  2> /dev/null)
```

## Additional examples that lead to segmentation fault
```
1.0 1 X
0.0 1 Z
```
```
0.0 1 Y
1.0 1 X
0.0 1 Z
```
```
1.0 1 X
0.0 1 Z
1.0 1 Y
```
## Another example that does NOT lead to segmentation fault
```
0.0 1 Y
1.0 1 X
```

**Comment by LevBarash** [comment]
This is now fixed.
